### ISSUE TITLE
My mctx project

### ISSUE THREAD

**Issue by NTT123** [google-deepmind/mctx#17]
Hi, thanks for the great library! Recently, I use `mctx` to train a simple Connect-four agent. 
The project is at https://github.com/NTT123/a0-jax

(A demo is also running at https://huggingface.co/spaces/ntt123/Connect-4-Game. It uses `tfjs` library to run the agent on the browser.)

I would be very glad if you can add this to your `example projects` list. Thank you!

**Comment by fidlej** [comment]
Thanks for mentioning your project. The Connect-4 demo is very nice.
I will mention your project in the mctx README. You can add the link to the demo to your README.

**Comment by fabioviola** [comment]
Thanks indeed for the link - this is fun!

**Comment by NTT123** [comment]
> Thanks for mentioning your project. The Connect-4 demo is very nice. I will mention your project in the mctx README. You can add the link to the demo to your README.

@fidlej, thanks! I've updated the readme with the link to the demo.
