### ISSUE TITLE
Two player games support?

### ISSUE THREAD

**Issue by uduse** [google-deepmind/mctx#24]
Will there be two player games support from `mctx`?

If I understand it correctly, technically it could possible to use the current `mctx` for two players. We may pass a flag indicating the current play in the root inference and flip the values based on the flag in the recurrent inference. Am I right?

**Comment by fidlej** [comment]
The two players with alternating moves are already supported. We use discount=-1 to obtain the zero-sum returns.

For example, @NTT123 used Mctx in an agent for Connect 4 and Go:
https://github.com/NTT123/a0-jax

**Comment by uduse** [comment]
> The two players with alternating moves are already supported. We use discount=-1 to obtain the zero-sum returns.
> 
> For example, @NTT123 used Mctx in an agent for Connect 4 and Go: https://github.com/NTT123/a0-jax

Oh I didn't know this, thank you for your explanation 👍
