### ISSUE TITLE
[Question] invalid action mask in interior action selection?

### ISSUE THREAD

**Issue by honglu2875** [google-deepmind/mctx#29]
Hello! First thank you guys for this repo. I learned a lot about JAX and MuZero from reading the codes. I plan to use this library on our [project](https://github.com/honglu2875/hironaka) soon to hopefully solve some math problems.

Just a question about the invalid action mask. I noticed that you have the invalid action at root nodes but not the interior nodes. Is not introducing interior action mask part of the features of being rule agnostic (there is a sentence in MuZero paper saying MuZero "learns" the rules)? Or is one still recommended to go ahead and rewrite a few functions to add masks for the interior action selection? 

I should be able to rewrite the [`gumbel_muzero_interior_action_selection`](https://github.com/deepmind/mctx/blob/8dac10f39786f13122785dd03b5ddcd3e393a655/mctx/_src/action_selection.py#L103) to achieve this, but since you have such an API only for roots, I'm asking to make sure that this is still the best practice and doesn't go against the purpose of the algorithm.

If it's the latter case, do you plan to expand features in that direction? Would love to help if there is the opportunity.

**Comment by fidlej** [comment]
Thanks for asking.
If you know which interior actions are invalid, you can give them zero probability from the policy network. For example, by assigning them logit=-1e9. This should be enough if using Gumbel MuZero (or Gumbel AlphaZero).

**Comment by honglu2875** [comment]
Ah Indeed!!
But does this also mean the invalid action mask for root is also redundant or was it designed for other purposes?

**Comment by fidlej** [comment]
The invalid action mask at the root seems useful in a few cases:
a) For UCT-like algorithms that do not use the policy network.
b) The sequential halving in Gumbel MuZero also needs to know the number of valid actions. We considered detecting that based on some threshold for the action log-probabilities. The usage of the invalid action mask may be less magical there.

**Comment by honglu2875** [comment]
Gotcha, thanks!
