### ISSUE TITLE
No pip install?

### ISSUE THREAD

**Issue by richardrl** [google-deepmind/mctx#34]
There currently doesn't seem to be any pip available.

```
pip install mctx

ERROR: Could not find a version that satisfies the requirement mctx (from versions: none)
ERROR: No matching distribution found for mctx
```

Using Ubuntu 18, Python 3.6

**Comment by fidlej** [comment]
Thanks for reporting the problem.
The mctx package requires Python >=3.7.
You would also need Python >=3.7 for JAX.
