### ISSUE TITLE
best practices for speed

### ISSUE THREAD

**Issue by wcarvalho** [google-deepmind/mctx#48]
Hey, thanks for this amazing library.

Question: are there any best practices for ensuring that MCTX is fast? I find it quite slow and was curious if there's common gotchas I might be missing.

**Comment by fidlej** [comment]
Hi Wilka. Do you have an example of your code? I assume that you use jit. How many simulations do you use? With Gumbel MuZero you can train even with 2 simulations.

**Comment by wcarvalho** [comment]
Thank you, that's helpful.
