### ISSUE TITLE
qtransform_by_min_max example

### ISSUE THREAD

**Issue by wbrenton** [google-deepmind/mctx#49]
Is there an example of using the `qtransform_by_min_max`? I'm unsure how to use it without entirely re-implementing the `mctx._src.policies.muzero_policy`.

**Comment by fidlej** [comment]
On Go, with reward=-1 for a loss and reward=1 for a win, you can use:
```
qtransform=functools.partial(mctx.qtransform_by_min_max, min_value=-1.0, max_value=1.0)
```

I recommend to use the `gumbel_muzero_policy` with the default qtransform. It works well on many environments.

**Comment by palash04** [comment]
Hi @fidlej , What if I have intermediate reward? Say, the minimum intermediate reward is -500 and maximum intermediate reward is 500, so for a depth of 100 - is it like min_value=-50000.0, max_value=50000.0 needs to be passed in the mctx.qtransform_by_min_max function ?
```
qtransform=functools.partial(mctx.qtransform_by_min_max, min_value=-50000.0, max_value=50000.0)
```

Or is it that I pass minimum and maximum intermediate reward to this mctx.qtransform_by_min_max ?
```
qtransform=functools.partial(mctx.qtransform_by_min_max, min_value=-500.0, max_value=500.0)
```

**Comment by fidlej** [comment]
You can use the gumbel_muzero_policy with the default qtransform_completed_by_mix_value. It will rescale the Q-values based on the Q-values for this node.

**Comment by palash04** [comment]
For qtransform_completed_by_mix_value, what should be the ideal "maxvisit_init: chex.Numeric = 50.0" ? Or should I leave every argument of this qtransform_completed_by_mix_value as is ?

**Comment by fidlej** [comment]
You can keep the defaults unchanged.
