### ISSUE TITLE
Questions on library features

### ISSUE THREAD

**Issue by AI3EL** [google-deepmind/mctx#56]
Hi, thank you for your work.

I am considering using it but I had a few questions before diving deeper:
- Does it support "multi-objective" that is having an array of rewards instead of a scalar (same for the discount factor) ?
- Does it support asynchronous (or delayed batch inference) mcts (using for instance virtual losses) ?
- How well does it behave when running on a non-vectorized cpu environment ?
- How well do you think it could be integrated into a ray parallel framework ? For instance if I have a remote inference server that gets called by several processes (each taking care of their own mcts tree) and batches the requests before redispatching them to the processes
- Does it perform well in single instance inference ?

Many Thanks

**Comment by fidlej** [comment]
Quick answers:
1. No support for an array of discounts.
2. The MCTS is synchronous. Parallel computation is done by using a batch size.
3. CPU works but would be probably slower.
4. I do not see a blocker. You would have to benchmark it to check that the speed is OK.
5. You would not benefit from the parallel computation with batch_size=1. On CPU, you can instead write an optimized MCTS in C++ or Rust.
