### ISSUE TITLE
New package version

### ISSUE THREAD

**Issue by ipsec** [google-deepmind/mctx#57]
Hi,

I'm installing mctx using  ```pip install mctx``` and the version available is 0.0.2 from Jul 26, 2022 by the commit [8dac10f](https://github.com/deepmind/mctx/commit/8dac10f39786f13122785dd03b5ddcd3e393a655)
Could you bump the version to 0.0.3 to apply last commits?

**Comment by fidlej** [comment]
Which feature do you miss?
The commits included:
1. Stochastic MuZero (experimental, not well tested)
2. Silencing some pylint and pytype errors.

**Comment by ipsec** [comment]
I want to use Stochastic MuZero (1) feature.
