### ISSUE TITLE
What is "millions of frames" in the plots in the paper?

### ISSUE THREAD

**Issue by p3achyjr** [google-deepmind/mctx#58]
Hello, thank you again for the paper and the associated code :)

I noticed that in the paper, most plots use "millions of frames" on the x-axis:

<img width="123" alt="image" src="https://github.com/deepmind/mctx/assets/8763808/61d09fa5-1589-4bb9-82ec-456e67ec8d8f">

What does this metric mean? Is it number of NN queries, number of games, training examples, or something else entirely?

**Comment by fidlej** [comment]
Thanks for asking. It is the number of frames generated by the environment. For example, on Atari, we count also the skipped frames.
