### ISSUE TITLE
Request to add link to Pgx repository in README

### ISSUE THREAD

**Issue by sotetsuk** [google-deepmind/mctx#65]
Hello,

I hope this message finds you well. I am reaching out to kindly request the addition of a link to my project, [Pgx](http://github.com/sotetsuk/pgx), in the README file of the Mctx repository.

Pgx is a collection of vectorized board game environments written in JAX, featuring over 20 games including backgammon, chess, shogi, and Go. The repository also includes an AlphaZero example by Mctx, showcasing reasonable learning in Go 9x9 and other medium-sized games.

I believe this link would be a valuable addition for Mctx users, providing them with easy access to a collection of JAX-native game environments as testbed.

Thank you for considering my request. I look forward to your positive response.

Best,

**Comment by fidlej** [comment]
Pgx is very nice! Thanks for sharing.
I will add the link.

BTW, when using [rescale_values=False](https://github.com/sotetsuk/pgx/blob/4962c492a21b51ece39e9cf3f16bc03be2fc71c2/examples/alphazero/train.py#L136C17-L136C31), you may get better results with value_scale=1.0. That will match the usage from the Gumbel MuZero paper.
