### ISSUE TITLE
A possible memory leak when use not_jitted mode in policy_imporvement_demo.py

### ISSUE THREAD

**Issue by hejujie** [google-deepmind/mctx#7]
I am using gumbel_muzero_policy without jit, and find a memory leak, so I try to use `tracemalloc` to trace the memory in policy_improvement_demo.py.
When I remove `jax.jit` in the main function and print the memory allocation, it keep increasing.
<img width="690" alt="image" src="https://user-images.githubusercontent.com/29149911/161363238-230067d2-7570-4e1b-90aa-8f349b03613f.png">
when I make it jit:
<img width="698" alt="image" src="https://user-images.githubusercontent.com/29149911/161363371-09080e45-cdf2-4824-96bc-25b4c0650c32.png">

I don't know whether this is a feature of JAX, or how can I clean memory by myself in not-jitted mode ?
Here is the change of code:
```python
import tracemalloc

def main(_):
    rng_key = jax.random.PRNGKey(FLAGS.seed)
    # the different is just next two line, jit or not;
    run_demo = jax.jit(_run_demo)
    # run_demo = _run_demo
    tracemalloc.start(10)
    snapshot1 = tracemalloc.take_snapshot()
    for _ in range(FLAGS.num_runs):
        rng_key, output = run_demo(rng_key)
        snapshot2 = tracemalloc.take_snapshot()
        top_stats = snapshot2.compare_to(snapshot1, 'lineno')
        total = sum(stat.size for stat in top_stats)
        print("Total allocated size: %.1f MiB" % (total / 1024 / 1024))

if __name__ == "__main__":
    app.run(main)
```

**Comment by hejujie** [comment]
The background why I am using not-jit mode is shown in this issue: https://github.com/deepmind/mctx/issues/6
I want to use a TensorFlow function in MCTX and I try to use jax2tf.call_tf or tf2jax.convert to compile my recurrent_inference_function in MuZero.
They report an error in jit-mode but run normally in not-jit mode (memory leak makes it crash after two-hour training）
`
TypeError: Argument '<jax._src.custom_derivatives.custom_vjp object at 0x7f5ec3cabc50>' of type <class 'jax._src.custom_derivatives.custom_vjp'> is not a valid JAX type.
`
I also try to read the JAX document and search for information about `custom_vjp` but can't find a useful solution.
Is there any material about how to solve this problem?  
Or is there another solution to avoid passing the recurrent function to jit-function?  Maybe I can just avoid jitting the expand function in mcts?

**Comment by hejujie** [comment]
> The background why I am using not-jit mode is shown in this issue: #6 I want to use a TensorFlow function in MCTX and I try to use jax2tf.call_tf or tf2jax.convert to compile my recurrent_inference_function in MuZero. They report an error in jit-mode but run normally in not-jit mode (memory leak makes it crash after two-hour training） `TypeError: Argument '<jax._src.custom_derivatives.custom_vjp object at 0x7f5ec3cabc50>' of type <class 'jax._src.custom_derivatives.custom_vjp'> is not a valid JAX type.` I also try to read the JAX document and search for information about `custom_vjp` but can't find a useful solution. Is there any material about how to solve this problem? Or is there another solution to avoid passing the recurrent function to jit-function? Maybe I can just avoid jitting the expand function in mcts?


class 'jax._src.custom_derivatives.custom_vjp'> is not a valid JAX type： this problem is solved by using `jax.tree_util.Partial`

**Comment by fidlej** [comment]
Thanks for the update. Are you now able to use jit for the computation?
The library is designed for the usage with jit. For example, some arrays are precomputed on the first run and then kept as constants inside the compiled graph.
