### ISSUE TITLE
Automatically determine num_actions and num_chance_outcomes in stochastic_muzero_policy

### ISSUE THREAD

**Issue by carlosgmartin** [google-deepmind/mctx#71]
It is possible to automatically determine the `num_actions` and `num_chance_outcomes` parameters to [`stochastic_muzero_policy`](https://github.com/google-deepmind/mctx/blob/main/mctx/_src/policies.py#L234C5-L234C29) from the `root`, `decision_recurrent_fn`, and `chance_recurrent_fn` parameters, via `ChanceRecurrentFnOutput.action_logits.shape` and `DecisionRecurrentFnOutput.chance_logits.shape`. That would reduce the number of parameters that users need to pass in by two.

I suggest allowing `num_actions` and `num_chance_outcomes` to be `None`, making them `None` by default, and determining their values automatically if they're `None`. This preserves backward compatibility. Thoughts?

**Comment by fidlej** [comment]
Thanks for the suggestions. It sounds good.
We do not need to preserve the backward compatibility with the None defaults. The stochastic_muzero_policy is still experimental.

Will you send a pull request or should I do that?

**Comment by fidlej** [comment]
Thanks for the improvements.
