### ISSUE TITLE
muzero_policy   is much slower than gumbel_muzero_policy

### ISSUE THREAD

**Issue by Nightbringers** [google-deepmind/mctx#81]
I found the time cost use method muzero_policy is much longer than gumbel_muzero_policy in same num_simulations, roughly three times as much. is this normal? and why?

**Comment by fidlej** [comment]
It probably depends on the usage, hardware, the size of the used networks, ...
You can use the JAX profile to know why:
https://jax.readthedocs.io/en/latest/profiling.html
 
I'm happy that gumbel_muzero_policy is not slower. You will probably get better results with the gumbel_muzero_policy.
