### ISSUE TITLE
Demo passing and indexing with recurrent_fn while del params and rng_key.

### ISSUE THREAD

**Issue by linjing-lab** [google-deepmind/mctx#98]
Acknowledged about Monte Carlo Tree Search from Tsuda Laboratory in description of ChemTS, params and rng_key of recurrent_fn passed through gumbel_muzero_policy to search to expand, interpret del keyword and qvalues in recurrent_fn of expand, which lines at L112 of recurrent_fn local space of examples/policy_improvement_demo.py,
```python
def recurrent_fn(params, rng_key, action, embedding):
    del params, rng_key
# L113-L128
```
Actual execution located at expand function of _src/search.py, which lines at L226 of recurrent_fn text, search_rng passing and indexing by assigned of stack values from `rng_key=search_rng` of mctx.gumbel_muzero_policy, one explain maybe dynamics network leverages recurrent state from del params based rng_key fixed runtime memory, cluster executes each rng_key localized functions in process.
```python
step, embedding = recurrent_fn(params, rng_key, action, embedding)
```

**Comment by fidlej** [comment]
Hi. I'm not sure I understood your description correctly. Do you want to know why the params and rng_key are deleted?

In the demo, the params and rng_key are not used, so they can be deleted. In a real usage, the params would be passed to a neural network. You can look at some example projects listed in the README.md:
https://github.com/google-deepmind/mctx/blob/main/README.md#example-projects
